// Master Level 7 E2E: real Tauri/WebView2/React/typed IPC/SQLite over bounded test-only fixtures.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {closeSync,existsSync,mkdirSync,openSync,readFileSync,readdirSync,realpathSync,statSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {setTimeout as delay} from 'node:timers/promises';

const root=realpathSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'));
const ledger=realpathSync(process.env.EDY_E2E_LEDGER??'');
assert(ledger.startsWith(path.resolve(root,'_intake')+path.sep));
assert.equal(process.platform,'win32');
const elementKey='element-6066-11e4-a52e-4f735466cecf';
const stamp=Date.now().toString().slice(-13);
const viewports=['1366x768','1920x1080','2560x1440'];
const publicationScreenshotDir=process.env.EDY_PUBLICATION_SCREENSHOT_DIR?path.resolve(process.env.EDY_PUBLICATION_SCREENSHOT_DIR):null;
const publicationScreenshots=new Map([
  ['Home','01-home.png'],
  ['Repository','02-repository-scan.png'],
  ['File/Binary','03-file-analysis.png'],
  ['Installed Apps Result','04-installed-apps.png'],
  ['Web/URL Result','05-web-url.png'],
  ['Case Detail','06-investigation.png'],
  ['Verification','07-remediation-guidance.png'],
  ['Diagnostics','08-report-or-diagnostics.png'],
]);
const sentinels=['EDY_FINAL_FAKE_SECRET','EDY_FINAL_FAKE_PASSWORD','EDY_FINAL_FAKE_COOKIE','EDY_FINAL_FAKE_QUERY','EDY_FINAL_FAKE_API_KEY','EDY_FINAL_FAKE_PRIVATE_KEY'];
const uiMatrix=[],runs=[],hostile=[];
let browser,app;

class Element{constructor(driver,id){this.driver=driver;this.id=id}command(p,m='GET',b){return this.driver.request(`/element/${this.id}${p}`,m,b)}click(){return this.command('/click','POST',{})}sendKeys(value){return this.command('/value','POST',{text:value,value:[value]})}getText(){return this.command('/text')}isEnabled(){return this.command('/enabled')}}
class Driver{constructor(id){this.id=id}static async connect(){const r=await fetch('http://127.0.0.1:4445/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({capabilities:{alwaysMatch:{browserName:'tauri','wdio:tauriServiceOptions':{windowLabel:'main'}},firstMatch:[{}]}})});const b=await r.json();if(!r.ok)throw Error(JSON.stringify(b));return new Driver(b.value.sessionId)}async request(p,m='GET',b){const r=await fetch(`http://127.0.0.1:4445/session/${this.id}${p}`,{method:m,headers:{'content-type':'application/json'},body:b===undefined?undefined:JSON.stringify(b)});const value=await r.json();if(!r.ok)throw Error(JSON.stringify(value));return value.value}async elements(selector){return(await this.request('/elements','POST',{using:'css selector',value:selector})).map(value=>new Element(this,value[elementKey]))}async button(label){for(const element of await this.elements('button'))if(await element.getText()===label)return element;throw Error(`button ${label} missing`)}execute(fn,...args){return this.request('/execute/sync','POST',{script:`return (${fn.toString()}).apply(null, arguments);`,args})}executeAsync(fn,...args){return this.request('/execute/async','POST',{script:`return (${fn.toString()}).apply(null, arguments);`,args})}keys(actions){return this.request('/actions','POST',{actions:[{type:'key',id:'keyboard',actions}]})}screenshot(){return this.request('/screenshot')}deleteSession(){return this.request('','DELETE')}}
async function until(fn,label,timeout=30000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{const value=await fn();if(value)return value}catch(error){last=error}await delay(80)}throw Error(`timeout ${label}: ${last?.message??''}`)}
const body=()=>browser.execute(()=>document.body.innerText);
async function click(label){const e=await browser.button(label);assert(await e.isEnabled(),`${label} disabled`);await e.click()}
async function input(label,value){await browser.execute((name,text)=>{const field=[...document.querySelectorAll('input')].find(item=>item.getAttribute('aria-label')===name||item.closest('label')?.textContent?.includes(name));if(!field)throw Error(`input ${name} missing`);const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(field,text);field.dispatchEvent(new Event('input',{bubbles:true}));},label,value)}
async function select(label,value){await browser.execute((name,next)=>{const field=[...document.querySelectorAll('select')].find(item=>item.getAttribute('aria-label')===name||item.closest('label')?.textContent?.includes(name));if(!field)throw Error(`select ${name} missing`);const setter=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;setter.call(field,next);field.dispatchEvent(new Event('change',{bubbles:true}));},label,value)}
async function rawIpc(command,request={}){return browser.executeAsync((cmd,payload,done)=>window.__TAURI_INTERNALS__.invoke(cmd,{request:payload}).then(value=>done({ok:true,value}),error=>done({ok:false,error})),command,request)}
async function ipc(command,request={}){const result=await rawIpc(command,request);assert(result.ok,`${command}: ${JSON.stringify(result)}`);return result.value}
async function terminal(id){return until(async()=>{const value=await ipc('get_scan_progress',{scan_id:id});return ['cancelled','completed','partial','failed'].includes(value.status)?value:false},`terminal ${id}`,60000)}
async function newScan(action){await action();await click('Scan Progress');await until(async()=>(await browser.execute(()=>document.querySelector('#title')?.textContent))==='Scan Progress','scan progress page');const id=await until(()=>browser.execute(()=>document.querySelector('main progress')?.closest('section')?.querySelector('code')?.textContent||false),'new selected scan');return{id}}
function clean(value,label){const text=typeof value==='string'?value:JSON.stringify(value);for(const sentinel of sentinels)assert(!text.includes(sentinel),`${label}: ${sentinel} leaked`);}
function persistedScanCount(database){const db=new DatabaseSync(database,{readOnly:true});try{return ['level0_snapshots','level1_repository_snapshots','level2_file_snapshots','level3_installed_app_snapshots','level4_web_snapshots'].reduce((total,table)=>total+Number(db.prepare(`SELECT count(*) AS n FROM ${table}`).get().n),0);}finally{db.close()}}

async function capture(viewport,screen){const result=await browser.execute(()=>{const failures=[];for(const element of document.querySelectorAll('button,input,select,main article,main table,main pre')){const r=element.getBoundingClientRect(),s=getComputedStyle(element);if(s.display==='none'||r.width===0||r.height===0)continue;if(r.left < -1||r.right>innerWidth+1)failures.push(`clipped:${element.tagName}:${element.textContent?.slice(0,30)}`);if(['BUTTON','INPUT','SELECT'].includes(element.tagName)&&element.getAttribute('type')!=='checkbox'&&r.height<24)failures.push(`small-target:${element.tagName}`)}const accessible=[...document.querySelectorAll('button,input,select')].every(element=>Boolean(element.getAttribute('aria-label')||element.textContent?.trim()||element.closest('label')?.textContent?.trim()));return{width:innerWidth,height:innerHeight,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),failures,accessible,raw_key:/\b(?:translation|i18n)\.[a-z0-9_.-]+\b/i.test(document.body.innerText),undefined_text:/\bundefined\b|\[object Object\]/.test(document.body.innerText)}});
  const row={viewport,screen,...result,result:result.overflow===0&&result.failures.length===0&&result.accessible&&!result.raw_key&&!result.undefined_text?'PASS':'FAIL'};uiMatrix.push(row);assert.equal(row.result,'PASS',JSON.stringify(row));
  const screenshotName=publicationScreenshots.get(screen);
  if(publicationScreenshotDir&&viewport==='1920x1080'&&screenshotName){
    await browser.execute(projectRoot=>{const generic='C:\\Synthetic\\EDY-VERDICT';const portable=projectRoot.replaceAll('\\','/');const sanitize=value=>value.replaceAll(projectRoot,generic).replaceAll(portable,generic.replaceAll('\\','/'));const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);for(let node=walker.nextNode();node;node=walker.nextNode())node.nodeValue=sanitize(node.nodeValue??'');for(const field of document.querySelectorAll('input'))field.value=sanitize(field.value);},root);
    mkdirSync(publicationScreenshotDir,{recursive:true});writeFileSync(path.join(publicationScreenshotDir,screenshotName),Buffer.from(await browser.screenshot(),'base64'));
  }
  return row;}

async function launch(viewport,runId,label){const out=openSync(path.join(ledger,`level7-${stamp}-${viewport}-${label}.stdout.log`),'wx'),err=openSync(path.join(ledger,`level7-${stamp}-${viewport}-${label}.stderr.log`),'wx');const started=Date.now();app=spawn(path.join(root,'target','debug','edy-desktop.exe'),[`--level7-native-qa=${viewport}`],{cwd:root,env:{...process.env,EDY_LEVEL7_E2E_RUN_ID:runId},windowsHide:true,stdio:['ignore',out,err]});closeSync(out);closeSync(err);await until(()=>fetch('http://127.0.0.1:4445/status',{signal:AbortSignal.timeout(500)}).then(r=>r.ok,()=>false),'webdriver',15000);browser=await Driver.connect();const first=await body();await until(async()=>/(Infraestrutura disponível|Infrastructure available)/.test(await body()),'foundation');return{startup_ms:Date.now()-started,initial_loading:/Validando infraestrutura|Validating infrastructure/.test(first)}}
async function stop(){if(browser){await browser.deleteSession().catch(()=>{});browser=null}if(app){const process=app;app=null;if(process.exitCode===null){process.kill();await Promise.race([once(process,'exit'),delay(10000)])}}await delay(250)}
function prepare(runId){const qa=path.join(root,'.local',`level7-product-native-qa-data-${runId}`),fixtures=path.join(qa,'final-fixtures'),repo=path.join(fixtures,'repository'),remediation=path.join(qa,'synthetic-remediation-repo'),associated=path.join(qa,'synthetic-associated-repo');mkdirSync(repo,{recursive:true});mkdirSync(remediation,{recursive:true});mkdirSync(associated,{recursive:true});const marker=sentinels.join(' ');writeFileSync(path.join(repo,'package.json'),JSON.stringify({name:'level7-fixture',version:'1.0.0',description:marker})+'\n');writeFileSync(path.join(repo,'package-lock.json'),'{"lockfileVersion":3}\n');writeFileSync(path.join(repo,'Cargo.toml'),'[package]\nname="level7-fixture"\nversion="0.1.0"\n');writeFileSync(path.join(repo,'Cargo.lock'),'version = 4\n');writeFileSync(path.join(repo,'.env.fixture'),marker+'\n');writeFileSync(path.join(fixtures,'benign.bin'),'EDY VERDICT bounded benign fixture\n');const remediationFixture=JSON.stringify({name:'controlled-fixture',version:'1.0.0',description:marker})+'\n';writeFileSync(path.join(remediation,'package.json'),remediationFixture);writeFileSync(path.join(associated,'package.json'),remediationFixture);return{qa,fixtures,repo,file:path.join(fixtures,'benign.bin'),database:path.join(qa,'level0.sqlite3')}}

async function navigate(label,screen,viewport){await click(label);await until(async()=>(await browser.execute(()=>document.querySelector('#title')?.textContent))===label,`page ${label}`);await capture(viewport,screen)}
async function invalidMatrix(){for(const [kind,command,request] of [
 ['url-private','preview_url_target',{url:'https://127.0.0.1/',query_policy:'strip'}],['url-userinfo','preview_url_target',{url:'https://user:pass@example.com/',query_policy:'strip'}],['url-scheme','preview_url_target',{url:'file:///C:/Windows/win.ini',query_policy:'strip'}],
 ['file-relative','inspect_file_target',{path:'relative.bin'}],['file-unc','inspect_file_target',{path:'\\\\server\\share\\x.bin'}],['file-device','inspect_file_target',{path:'\\\\.\\PhysicalDrive0'}],
 ['repository-relative','authorize_repository_target',{path:'relative-repository'}],
 ]){console.log(`hostile-check:${kind}`);const value=await rawIpc(command,request);hostile.push({kind,command,result:value.ok?'FAIL':'PASS'});assert.equal(value.ok,false,kind)}}

async function fullJourney(viewport,index){const runId=`${stamp.slice(-11)}${index}`;const fixture=prepare(runId);const start=await launch(viewport,runId,'journey');await capture(viewport,'First Run');if((await body()).includes('Entendi'))await click('Entendi');await capture(viewport,'Empty');await select('Idioma','en');await until(async()=>(await body()).includes('Infrastructure available'),'English locale');
  // Keyboard-only activation of About through the real WebDriver actions endpoint.
  await browser.execute(()=>{const button=[...document.querySelectorAll('nav button')].find(item=>item.textContent==='About');if(!button)throw Error('About navigation missing');button.focus();button.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true,cancelable:true}));});await until(async()=>(await browser.execute(()=>document.querySelector('#title')?.textContent))==='About','keyboard About');assert.equal(await browser.execute(()=>document.activeElement?.id),'title');await capture(viewport,'About');
  await navigate('Home','Home',viewport);await navigate('New Scan','New Scan',viewport);
  await input('Repository path',fixture.repo);await click('Authorize and inspect');await until(async()=>(await body()).includes('Authorization preview'),'repository preview');await capture(viewport,'Repository');const repository=await newScan(()=>click('Confirm repository scan'));await terminal(repository.id);
  await navigate('New Scan','New Scan after repository',viewport);await input('File path',fixture.file);await click('Preview file');await until(async()=>(await body()).includes('File preview'),'file preview');await click('Authorize this exact file');await until(async()=>(await body()).includes('Authorization captured'),'file auth');await capture(viewport,'File/Binary');const file=await newScan(()=>click('Confirm file analysis'));await terminal(file.id);
  await navigate('Installed Apps','Installed Apps',viewport);await click('Preview inventory');await until(async()=>(await body()).includes('applications in preview'),'app preview');await click('Authorize this snapshot');await until(async()=>(await body()).includes('Snapshot authorized'),'app auth');const installed=await newScan(()=>click('Confirm installed-app analysis'));await terminal(installed.id);await navigate('Installed Apps','Installed Apps Result',viewport);await until(async()=>(await body()).includes('Inventory coverage'),'app inventory');
  await navigate('Web / URL','Web/URL',viewport);await input('Web URL',`https://redirect.example/path?token=${sentinels[3]}#private`);await click('Validate target');await until(async()=>(await body()).includes('Sanitized preview'),'url preview');clean(await body(),'URL preview');await click('Authorize this exact sanitized target');await until(async()=>(await body()).includes('URL authorization captured'),'url auth');const web=await newScan(()=>click('Confirm passive URL analysis'));await terminal(web.id);await navigate('Web / URL','Web/URL Result',viewport);await until(async()=>(await body()).includes('Cookie attributes'),'web result');clean(await body(),'web DOM');
  await navigate('History','Scan Result',viewport);await navigate('Findings','Finding',viewport);await navigate('Reports','Reports',viewport);await click('Generate report: Technical');await until(async()=>(await body()).includes('product_version'),'versioned report');const reportText=await body();assert(reportText.includes('1.0.0-rc.1'));clean(reportText,'report DOM');
  await navigate('Investigations','Investigations',viewport);await click('Run correlation');await until(async()=>(await body()).includes('Correlated findings'),'correlation');await capture(viewport,'Case Detail');
  await navigate('Remediation','Remediation Guidance',viewport);await until(async()=>!(await body()).includes('Guidance data is unavailable'),'remediation load');const creates=await browser.elements('button');if((await Promise.all(creates.map(item=>item.getText()))).includes('Create remediation plan')){await click('Create remediation plan');await until(async()=>(await body()).includes('Review remediation guidance'),'plan');await click('View guidance and suggested diff');await until(async()=>(await body()).includes('Suggested change'),'guidance');await capture(viewport,'Verification');}assert(!(await body()).includes('Apply this remediation'));assert(!(await body()).includes('Roll back'));
  await navigate('Settings','Settings',viewport);await click('Privacy');await until(async()=>(await browser.execute(()=>document.querySelector('#title')?.textContent))==='Privacy','privacy');await capture(viewport,'Privacy');await click('Settings');await click('Diagnostics');await until(async()=>(await browser.execute(()=>document.querySelector('#title')?.textContent))==='Diagnostics','diagnostics');await capture(viewport,'Diagnostics');
  await browser.execute(()=>{Object.defineProperty(Navigator.prototype,'onLine',{configurable:true,get:()=>false});dispatchEvent(new Event('offline'));});await until(async()=>(await body()).includes('Offline mode'),'offline mode');await capture(viewport,'Offline');assert((await body()).includes('Recorded local scans'));
  await navigate('New Scan','Loading',viewport);await input('File path','Z:\\does-not-exist\\final.bin');await click('Preview file');await until(async()=>(await body()).includes('The operation did not complete'),'safe error');await capture(viewport,'Error');
  await invalidMatrix();const beforeRestart=persistedScanCount(fixture.database);assert(beforeRestart>=4,'all scan kinds must be persisted');await stop();const restarted=await launch(viewport,runId,'restart');await browser.execute(()=>localStorage.setItem('edy-verdict.locale','en'));await until(async()=>(await body()).includes('Infrastructure available'),'restart ready');await click('History');await until(async()=>(await browser.execute(()=>document.querySelectorAll('main tbody tr').length))>=4,'persisted history');const afterRestart=persistedScanCount(fixture.database);assert.equal(afterRestart,beforeRestart);const db=new DatabaseSync(fixture.database,{readOnly:true});const integrity=db.prepare('PRAGMA integrity_check').get().integrity_check;const version=db.prepare('PRAGMA user_version').get().user_version;db.close();assert.equal(integrity,'ok');assert.equal(version,8);for(const fileName of readdirSync(fixture.qa)){const candidate=path.join(fixture.qa,fileName);if(statSync(candidate).isFile()&&!candidate.startsWith(fixture.fixtures))clean(readFileSync(candidate),`persisted ${fileName}`)}await stop();runs.push({viewport,runId,startup_ms:start.startup_ms,restart_ms:restarted.startup_ms,initial_loading_observed:start.initial_loading,scans:afterRestart,sqlite_integrity:integrity,schema_version:version,persistence:'PASS',external_requests:0,result:'PASS'});}

let failure;
try{for(let index=0;index<viewports.length;index++)await fullJourney(viewports[index],index);}catch(error){failure=error;console.error(error);if(browser)console.error(await body().catch(()=>''));}
finally{await stop();for(const fileName of readdirSync(ledger).filter(name=>name.startsWith(`level7-${stamp}`)&&name.endsWith('.log')))clean(readFileSync(path.join(ledger,fileName),'utf8'),`log ${fileName}`);const result={schema:'EDY_LEVEL7_MASTER_E2E_V1',status:failure?'FAIL':'PASS',product_version:'1.0.0-rc.1',runs,uiMatrix,hostile,redaction:failure?'INCOMPLETE':'PASS',actual_tauri:true,actual_webview2:true,actual_react:true,actual_typed_ipc:true,actual_sqlite:true,mocked_ipc:false,real_engines_executed:false,external_requests:0,failure:failure?{message:failure.message}:null};writeFileSync(path.join(ledger,'LEVEL7_MASTER_E2E_RESULT.json'),JSON.stringify(result,null,2)+'\n');}
if(failure)process.exitCode=1;else console.log('LEVEL 7 MASTER NATIVE E2E PASS');
