// Real Tauri/WebView2 Level 4 E2E. Fixed synthetic network fixture; no external request.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {setTimeout as delay} from 'node:timers/promises';
import {closeSync,existsSync,openSync,readFileSync,realpathSync,renameSync,writeFileSync} from 'node:fs';
import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=realpathSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'));
const ledger=realpathSync(process.env.EDY_E2E_LEDGER??'');assert(ledger.startsWith(path.resolve(root,'../_intake')+path.sep));assert.equal(process.platform,'win32');
const elementKey='element-6066-11e4-a52e-4f735466cecf';const runId=Date.now().toString();const matrix=[];let browser;let app;
class Element{constructor(driver,id){this.driver=driver;this.id=id;}command(p,m='GET',b){return this.driver.request(`/element/${this.id}${p}`,m,b)}click(){return this.command('/click','POST',{})}getText(){return this.command('/text')}isEnabled(){return this.command('/enabled')}}
class Driver{constructor(id){this.id=id}static async connect(){const r=await fetch('http://127.0.0.1:4445/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({capabilities:{alwaysMatch:{browserName:'tauri','wdio:tauriServiceOptions':{windowLabel:'main'}},firstMatch:[{}]}})});const b=await r.json();if(!r.ok)throw Error(JSON.stringify(b));return new Driver(b.value.sessionId)}async request(p,m='GET',b){const r=await fetch(`http://127.0.0.1:4445/session/${this.id}${p}`,{method:m,headers:{'content-type':'application/json'},body:b===undefined?undefined:JSON.stringify(b)});const v=await r.json();if(!r.ok)throw Error(JSON.stringify(v));return v.value}async elements(selector){return(await this.request('/elements','POST',{using:'css selector',value:selector})).map(v=>new Element(this,v[elementKey]))}async button(label){for(const e of await this.elements('button'))if(await e.getText()===label)return e;throw Error(`button ${label} missing`)}execute(fn,...args){return this.request('/execute/sync','POST',{script:`return (${fn.toString()}).apply(null, arguments);`,args})}executeAsync(fn,...args){return this.request('/execute/async','POST',{script:`return (${fn.toString()}).apply(null, arguments);`,args})}deleteSession(){return this.request('','DELETE')}}
async function until(fn,label,timeout=30000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{const v=await fn();if(v)return v}catch(e){last=e}await delay(80)}throw Error(`timeout ${label}: ${last?.message??''}`)}
const body=()=>browser.execute(()=>document.body.innerText);async function click(label){const e=await browser.button(label);assert(await e.isEnabled());await e.click()}
async function ipc(command,request=null){const allowed=['get_foundation_status','list_scans','get_scan_progress','preview_url_target','authorize_url_target','create_url_scan','cancel_scan','get_url_scan_analysis','generate_report'];assert(allowed.includes(command));const r=await browser.executeAsync((c,q,done)=>window.__TAURI_INTERNALS__.invoke(c,q===null?{}:{request:q}).then(value=>done({ok:true,value}),error=>done({ok:false,error})),command,request);assert(r.ok,JSON.stringify(r));return r.value}
async function terminal(scanId){return until(async()=>{const p=await ipc('get_scan_progress',{scan_id:scanId});return ['completed','partial','failed','cancelled'].includes(p.status)?p:false},`terminal ${scanId}`)}
async function screen(viewport,state){const layout=await browser.execute(()=>{const errors=[];for(const e of document.querySelectorAll('main button,main input,main select,main table,main article')){const r=e.getBoundingClientRect(),s=getComputedStyle(e);if(r.width===0||r.height===0||s.display==='none')continue;if(r.left< -1||r.right>innerWidth+1)errors.push({reason:'horizontal clipping',text:e.textContent?.slice(0,50)});if(parseFloat(s.fontSize)<10)errors.push({reason:'font below 10px',text:e.textContent?.slice(0,50)})}return{width:innerWidth,height:innerHeight,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),errors}});const row={viewport,state,...layout,result:layout.overflow===0&&layout.errors.length===0?'PASS':'FAIL'};matrix.push(row);assert.equal(row.result,'PASS',JSON.stringify(row))}
async function uiStart(url){await click('Web / URL');if((await browser.elements('input[aria-label="Web URL"]')).length===0)await click('Analyze another URL');await browser.execute((value)=>{const input=document.querySelector('input[aria-label="Web URL"]');const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}))},url);await click('Validate target');await until(async()=>(await body()).includes(new URL(url).hostname),'target preview');await click('Authorize this exact sanitized target');await until(async()=>(await body()).includes('URL authorization captured'),'target authorization');const old=(await ipc('list_scans',{offset:0,limit:50})).map(x=>x.id);await click('Confirm passive URL analysis');return until(async()=>(await ipc('list_scans',{offset:0,limit:50})).find(x=>!old.includes(x.id)),'new URL scan')}
function stored(scanId){const db=new DatabaseSync(path.join(root,'.local/level4-native-qa-data/level0.sqlite3'),{readOnly:true});try{const row=db.prepare('SELECT payload,payload_sha256 FROM level4_web_snapshots WHERE scan_id=?').get(scanId);assert(row);const bytes=Buffer.from(row.payload);assert.equal(String(row.payload_sha256),createHash('sha256').update(bytes).digest('hex'));return bytes.toString()}finally{db.close()}}
async function launch(viewport){const qa=path.join(root,'.local/level4-native-qa-data');if(existsSync(qa))renameSync(qa,`${qa}-archive-${runId}-${viewport}`);const out=openSync(path.join(ledger,`level4-${runId}-${viewport}.stdout.log`),'wx'),err=openSync(path.join(ledger,`level4-${runId}-${viewport}.stderr.log`),'wx');app=spawn(path.join(root,'target/debug/edy-desktop.exe'),[`--level4-native-qa=${viewport}`],{cwd:root,windowsHide:true,stdio:['ignore',out,err]});closeSync(out);closeSync(err);await until(()=>fetch('http://127.0.0.1:4445/status',{signal:AbortSignal.timeout(500)}).then(r=>r.ok,()=>false),'driver');browser=await Driver.connect();await until(async()=>(await body()).includes('Infraestrutura disponível'),'foundation')}
async function stop(){if(browser){await browser.deleteSession().catch(()=>{});browser=null}if(app){const p=app;app=null;if(p.exitCode===null){p.kill();await Promise.race([once(p,'exit'),delay(10000)])}}}
async function flow(viewport){await screen(viewport,'empty');await click('Web / URL');await until(async()=>(await body()).includes('Passive checks only'),'web page');await browser.execute((url)=>{const input=document.querySelector('input[aria-label="Web URL"]');const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,url);input.dispatchEvent(new Event('input',{bubbles:true}))},'https://redirect.example/path?token=EDY_FAKE_QUERY_SECRET_LEVEL4#private');await click('Validate target');await until(async()=>(await body()).includes('Sanitized preview'),'preview');let rendered=await body();assert(rendered.includes('https://redirect.example/path'));assert(rendered.includes('absent or stripped'));assert(!rendered.includes('EDY_FAKE_QUERY_SECRET_LEVEL4'));await screen(viewport,'preview');await click('Authorize this exact sanitized target');await until(async()=>(await body()).includes('URL authorization captured'),'authorization');const old=(await ipc('list_scans',{offset:0,limit:50})).map(x=>x.id);await click('Confirm passive URL analysis');const scan=await until(async()=>(await ipc('list_scans',{offset:0,limit:50})).find(x=>!old.includes(x.id)),'scan');const analysis=await until(async()=>{const v=await ipc('get_url_scan_analysis',{scan_id:scan.id});return v.analysis?v:false},'analysis');const serialized=JSON.stringify(analysis);assert(!serialized.includes('EDY_FAKE_QUERY_SECRET_LEVEL4'));assert(!serialized.includes('EDY_FAKE_COOKIE_SECRET_LEVEL4'));assert(analysis.analysis.dns.every(x=>x.state==='resolved_public_and_pinned'));assert(analysis.analysis.tls.every(x=>x.validation_enabled&&x.hostname_validation_enabled));assert.equal(analysis.analysis.redirects.length,1);assert.equal(analysis.analysis.redirects[0].followed,true);assert.equal(analysis.analysis.reputation.state,'unavailable_byok_not_configured');const persisted=stored(scan.id);assert(!persisted.includes('EDY_FAKE_QUERY_SECRET_LEVEL4'));assert(!persisted.includes('EDY_FAKE_COOKIE_SECRET_LEVEL4'));await until(async()=>(await body()).includes('Cookie attributes'),'analysis UI');rendered=await body();for(const label of ['DNS / Target','TLS','Security headers','Cookie attributes','Value never retained','Reputation','Coverage'])assert(rendered.includes(label));await screen(viewport,'analysis');await click('Relatórios');await click('Gerar relatório: Técnico');await until(async()=>(await body()).includes('LEVEL4_PASSIVE_WEB_REPORT_V1'),'report');const report=await ipc('generate_report',{scan_id:scan.id,kind:'developer'});assert.equal(JSON.parse(report.json).schema,'LEVEL4_PASSIVE_WEB_REPORT_V1');assert(!report.json.includes('EDY_FAKE_QUERY_SECRET_LEVEL4'));
const directBlocked=await uiStart('https://blocked.example/');assert.equal((await terminal(directBlocked.id)).status,'failed');assert.equal((await ipc('get_url_scan_analysis',{scan_id:directBlocked.id})).analysis,null);await until(async()=>(await body()).includes('stopped safely'),'direct SSRF UI error');await screen(viewport,'ssrf-blocked');
const redirectBlocked=await uiStart('https://redirect-private.example/');assert.equal((await terminal(redirectBlocked.id)).status,'failed');assert.equal((await ipc('get_url_scan_analysis',{scan_id:redirectBlocked.id})).analysis,null);await until(async()=>(await body()).includes('stopped safely'),'redirect SSRF UI error');
const downgrade=await uiStart('https://downgrade.example/');await terminal(downgrade.id);const downgradeAnalysis=(await ipc('get_url_scan_analysis',{scan_id:downgrade.id})).analysis;assert(downgradeAnalysis);assert.equal(downgradeAnalysis.redirects[0].outcome,'transport_downgrade');assert.equal(downgradeAnalysis.redirects[0].followed,false);await until(async()=>(await body()).includes('transport_downgrade'),'downgrade UI');await screen(viewport,'https-downgrade');
const cancelled=await uiStart('https://target.example/delay');await click('Progresso');await click('Cancelar');assert.equal((await terminal(cancelled.id)).status,'cancelled');assert.equal((await ipc('get_url_scan_analysis',{scan_id:cancelled.id})).analysis,null);await click('Web / URL');await until(async()=>(await body()).includes('analysis cancelled'),'cancelled UI');await screen(viewport,'cancelled');
return{viewport,scan_id:scan.id,direct_ssrf:'PASS',redirect_ssrf:'PASS',https_downgrade:'PASS',cancellation:'PASS',result:'PASS'}}
let failure,failureBody;const results=[];try{for(const viewport of(process.env.EDY_E2E_VIEWPORTS??'1366x768,1920x1080,2560x1440').split(',')){assert(['1366x768','1920x1080','2560x1440'].includes(viewport));await launch(viewport);results.push(await flow(viewport));await stop()}}catch(error){failure=error;failureBody=browser?await body().catch(()=>null):null;console.error(error,failureBody)}finally{await stop();writeFileSync(path.join(ledger,'LEVEL4_NATIVE_E2E_RESULT.json'),JSON.stringify({status:failure?'FAIL':'PASS',runId,results,matrix,failure:failure?{message:failure.message,body:failureBody}:null,actual_tauri:true,mocked_ipc:false,external_requests:0},null,2)+'\n')}
if(failure)process.exitCode=1;else console.log(`LEVEL 4 NATIVE E2E PASS: ${results.length} viewports, ${matrix.length} screens`);
