// Real Tauri/WebView2 Level 3 E2E. Synthetic installed-app fixture only; no host inventory leaves the process.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {setTimeout as delay} from 'node:timers/promises';
import {closeSync,existsSync,mkdirSync,openSync,readFileSync,realpathSync,renameSync,writeFileSync} from 'node:fs';
import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=realpathSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'));
const ledger=realpathSync(process.env.EDY_E2E_LEDGER??'');assert(ledger.startsWith(path.resolve(root,'../_intake')+path.sep),'external project ledger required');assert.equal(process.platform,'win32');
const elementKey='element-6066-11e4-a52e-4f735466cecf';const runId=Date.now().toString();const rows=[];let browser;let app;
class Element{constructor(driver,id){this.driver=driver;this.id=id;}command(p,m='GET',b){return this.driver.request(`/element/${this.id}${p}`,m,b)}click(){return this.command('/click','POST',{})}getText(){return this.command('/text')}isEnabled(){return this.command('/enabled')}}
class Driver{constructor(id){this.id=id}static async connect(){const r=await fetch('http://127.0.0.1:4445/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({capabilities:{alwaysMatch:{browserName:'tauri','wdio:tauriServiceOptions':{windowLabel:'main'}},firstMatch:[{}]}})});const b=await r.json();if(!r.ok)throw Error(JSON.stringify(b));return new Driver(b.value.sessionId)}async request(p,m='GET',b){const r=await fetch(`http://127.0.0.1:4445/session/${this.id}${p}`,{method:m,headers:{'content-type':'application/json'},body:b===undefined?undefined:JSON.stringify(b)});const v=await r.json();if(!r.ok)throw Error(JSON.stringify(v));return v.value}async elements(selector){return (await this.request('/elements','POST',{using:'css selector',value:selector})).map(v=>new Element(this,v[elementKey]))}async button(label){for(const e of await this.elements('button'))if(await e.getText()===label)return e;throw Error(`button ${label} missing`)}execute(fn,...args){return this.request('/execute/sync','POST',{script:`return (${fn.toString()}).apply(null, arguments);`,args})}executeAsync(fn,...args){return this.request('/execute/async','POST',{script:`return (${fn.toString()}).apply(null, arguments);`,args})}deleteSession(){return this.request('','DELETE')}}
async function until(fn,label,timeout=30000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{const value=await fn();if(value)return value}catch(error){last=error}await delay(80)}throw Error(`timeout ${label}: ${last?.message??''}`)}
const body=()=>browser.execute(()=>document.body.innerText);async function click(label){const e=await browser.button(label);assert(await e.isEnabled());await e.click()}
async function ipc(command,request=null){const allowed=['get_foundation_status','get_vulnerability_provider_status','list_scans','get_installed_application_inventory','get_installed_application','generate_report'];assert(allowed.includes(command));const result=await browser.executeAsync((c,q,done)=>window.__TAURI_INTERNALS__.invoke(c,q===null?{}:{request:q}).then(value=>done({ok:true,value}),error=>done({ok:false,error})),command,request);assert(result.ok,JSON.stringify(result));return result.value}
async function screen(viewport,state){const layout=await browser.execute(()=>{const errors=[];for(const e of document.querySelectorAll('main button,main input,main select,main table,main article')){const r=e.getBoundingClientRect(),s=getComputedStyle(e);if(r.width===0||r.height===0||s.display==='none')continue;if(r.left< -1||r.right>innerWidth+1)errors.push({reason:'horizontal clipping',text:e.textContent?.slice(0,50)});if(parseFloat(s.fontSize)<10)errors.push({reason:'font below 10px',text:e.textContent?.slice(0,50)})}return {width:innerWidth,height:innerHeight,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),errors}});const row={viewport,state,...layout,result:layout.overflow===0&&layout.errors.length===0?'PASS':'FAIL'};rows.push(row);assert.equal(row.result,'PASS',JSON.stringify(row))}
function stored(scanId){const db=new DatabaseSync(path.join(root,'.local/level3-native-qa-data/level0.sqlite3'),{readOnly:true});try{const row=db.prepare('SELECT payload,payload_sha256,revision FROM level3_installed_app_snapshots WHERE scan_id=?').get(scanId);assert(row);const bytes=Buffer.from(row.payload);assert.equal(String(row.payload_sha256).toLowerCase(),createHash('sha256').update(bytes).digest('hex'));return {payload:JSON.parse(bytes),revision:row.revision}}finally{db.close()}}
async function launch(viewport,mode='ready'){const qa=path.join(root,'.local/level3-native-qa-data');if(existsSync(qa))renameSync(qa,`${qa}-archive-${runId}-${viewport}-${mode}`);const out=openSync(path.join(ledger,`level3-${runId}-${viewport}-${mode}.stdout.log`),'wx'),err=openSync(path.join(ledger,`level3-${runId}-${viewport}-${mode}.stderr.log`),'wx');const flag=mode==='degraded'?`--level3-native-qa-degraded=${viewport}`:`--level3-native-qa=${viewport}`;app=spawn(path.join(root,'target/debug/edy-desktop.exe'),[flag],{cwd:root,windowsHide:true,stdio:['ignore',out,err]});closeSync(out);closeSync(err);await until(()=>fetch('http://127.0.0.1:4445/status',{signal:AbortSignal.timeout(500)}).then(r=>r.ok,()=>false),'driver');browser=await Driver.connect();await until(async()=>(await body()).includes('Infraestrutura disponível'),'foundation');assert.equal((await ipc('get_foundation_status')).ipc,'restricted')}
async function stop(){if(browser){await browser.deleteSession().catch(()=>{});browser=null}if(app){const p=app;app=null;if(p.exitCode===null){p.kill();await Promise.race([once(p,'exit'),delay(10000)])}}}
async function flow(viewport){
  await screen(viewport,'empty');await click('Aplicativos instalados');
  await until(async()=>(await body()).includes('Installed Application Security'),'page');await screen(viewport,'start');
  await click('Preview inventory');await until(async()=>(await body()).includes('applications in preview'),'preview');await screen(viewport,'preview');
  await click('Authorize this snapshot');await until(async()=>(await body()).includes('Snapshot authorized'),'authorization');
  await click('Authorize this snapshot');await until(async()=>(await body()).includes('Installed application authorization failed safely'),'safe authorization error');await screen(viewport,'error');
  const old=(await ipc('list_scans',{offset:0,limit:50})).map(scan=>scan.id);await click('Confirm installed-app analysis');
  const scan=await until(async()=>(await ipc('list_scans',{offset:0,limit:50})).find(item=>!old.includes(item.id)),'scan');
  const inventory=await until(async()=>{const value=await ipc('get_installed_application_inventory',{scan_id:scan.id});return value.state==='completed'?value:false},'completed installed-app scan');assert.equal(inventory.state,'completed');
  assert.deepEqual(inventory.provider_status.map(provider=>provider.state),['ready','ready','ready']);
  assert(inventory.snapshot.applications.some(application=>application.identity.state==='unmapped'));
  assert(inventory.findings.some(finding=>finding.kev&&finding.priority==='immediate'));
  assert(inventory.findings.some(finding=>finding.epss?.probability>=0.5));assert(inventory.findings.every(finding=>finding.affected==='affected'));
  assert.equal(stored(scan.id).payload.scan_id,scan.id);await until(async()=>(await body()).includes('CVE-2099-0001'),'inventory UI');
  const rendered=await body();for(const label of ['Fixture App','CVE-2099-0001','does not prove host exploitation','No finding does not mean clean'])assert(rendered.includes(label));
  await screen(viewport,'inventory-vulnerability-kev-epss-unmapped');await click('Relatórios');await click('Gerar relatório: Técnico');
  await until(async()=>(await body()).includes('LEVEL3_INSTALLED_APPLICATION_REPORT_V1'),'report');await screen(viewport,'report');
  const report=await ipc('generate_report',{scan_id:scan.id,kind:'developer'});assert.equal(JSON.parse(report.json).schema,'LEVEL3_INSTALLED_APPLICATION_REPORT_V1');
  return {viewport,scan_id:scan.id,applications:inventory.snapshot.applications.length,findings:inventory.findings.length,result:'PASS'};
}
async function cancellationFlow(viewport){
  await click('Aplicativos instalados');await click('Preview inventory');await until(async()=>await (await browser.button('Authorize this snapshot')).isEnabled(),'new preview');await click('Authorize this snapshot');await until(async()=>await (await browser.button('Confirm installed-app analysis')).isEnabled(),'new authorization');
  const old=(await ipc('list_scans',{offset:0,limit:50})).map(scan=>scan.id);await click('Confirm installed-app analysis');const scan=await until(async()=>(await ipc('list_scans',{offset:0,limit:50})).find(item=>!old.includes(item.id)),'cancellable scan');
  await click('Progresso');await until(async()=>await (await browser.button('Cancelar')).isEnabled(),'cancel button');await click('Cancelar');
  const inventory=await until(async()=>{const value=await ipc('get_installed_application_inventory',{scan_id:scan.id});return value.state==='cancelled'?value:false},'cancelled installed-app scan');assert.equal(inventory.findings.length,0);await until(async()=>(await body()).includes('cancelled'),'cancelled UI');await screen(viewport,'cancelled');return {viewport,scan_id:scan.id,result:'PASS'};
}
async function degradedFlow(viewport){await click('Aplicativos instalados');const rendered=await until(async()=>{const text=await body();return text.includes('stale_cache')&&text.includes('unavailable')?text:false},'degraded provider UI');assert(rendered.includes('stale_age_over_24h'));assert(rendered.includes('no_validated_cache'));await screen(viewport,'stale-and-provider-unavailable');return {viewport,result:'PASS'}}
let failure,failureBody;const results=[];const cancellations=[];let degraded;try{for(const viewport of (process.env.EDY_E2E_VIEWPORTS??'1366x768,1920x1080,2560x1440').split(',')){assert(['1366x768','1920x1080','2560x1440'].includes(viewport));await launch(viewport);results.push(await flow(viewport));cancellations.push(await cancellationFlow(viewport));await stop()}await launch('1366x768','degraded');degraded=await degradedFlow('1366x768');await stop()}catch(error){failure=error;failureBody=browser?await body().catch(()=>null):null;console.error(error,failureBody)}finally{await stop();writeFileSync(path.join(ledger,'LEVEL3_NATIVE_E2E_RESULT.json'),JSON.stringify({status:failure?'FAIL':'PASS',runId,results,cancellations,degraded,matrix:rows,failure:failure?{message:failure.message,body:failureBody}:null,actual_tauri:true,mocked_ipc:false,host_inventory_transmitted:false},null,2)+'\n')}
if(failure)process.exitCode=1;else console.log(`LEVEL 3 NATIVE E2E PASS: ${results.length} viewports, ${rows.length} screens`);
