import { invoke } from "@tauri-apps/api/core";

export type CaseStatus="suggested"|"open"|"investigating"|"remediating"|"verification_pending"|"resolved"|"accepted_risk"|"ignored";
export type CorrelationRunState="complete"|"partial_correlation"|"cancelled";
export interface CorrelationSummary{readonly run_id:string;readonly state:CorrelationRunState;readonly limit_reached:boolean;readonly replay_match:boolean;readonly nodes:number;readonly relationships:number;readonly clusters:number;readonly cases:number}
export interface Cluster{readonly cluster_id:string;readonly cluster_type:string;readonly member_findings:readonly string[];readonly member_entities:readonly string[];readonly supporting_edges:readonly string[];readonly target_count:number;readonly evidence_count:number;readonly first_seen:string;readonly last_seen:string;readonly explanation_safe:string}
export interface TimelineEvent{readonly sequence:number;readonly timestamp:string;readonly event_type:string;readonly summary_safe:string;readonly source:string}
export interface CaseTransition{readonly from:CaseStatus;readonly to:CaseStatus;readonly timestamp:string;readonly actor_source:string;readonly reason_safe:string}
export interface InvestigationCase{readonly case_id:string;readonly title_safe:string;readonly status:CaseStatus;readonly suggested:boolean;readonly finding_ids:readonly string[];readonly cluster_ids:readonly string[];readonly entity_ids:readonly string[];readonly evidence_ids:readonly string[];readonly blast_radius:{readonly observed_only:true;readonly unique_affected_targets:number;readonly unique_affected_components:number;readonly unique_findings:number;readonly unique_vulnerability_ids:number;readonly target_types_affected:readonly string[]};readonly assessment:{readonly risk:number;readonly confidence:number;readonly coverage:number;readonly priority:string;readonly risk_reasons:readonly string[];readonly confidence_reasons:readonly string[];readonly coverage_reasons:readonly string[];readonly priority_reasons:readonly string[]};readonly timeline:readonly TimelineEvent[];readonly transitions:readonly CaseTransition[]}
export interface Relationship{readonly edge_id:string;readonly relationship:string;readonly from_entity:string;readonly to_entity:string;readonly rule_id:string;readonly rule_version:number;readonly finding_ids:readonly string[];readonly evidence_ids:readonly string[];readonly source_scans:readonly string[];readonly created_by:string;readonly confidence:number;readonly reasoning_safe:string;readonly schema_version:number}
export interface InvestigationGraph{readonly schema:"LEVEL5_INVESTIGATION_V1";readonly state:"complete";readonly limit_reached:false;readonly nodes:readonly {readonly entity_id:string;readonly schema:string;readonly kind:string;readonly identity:{readonly kind:string;readonly canonical_value:string};readonly label_safe:string}[];readonly edges:readonly Relationship[];readonly clusters:readonly Cluster[];readonly suggested_cases:readonly InvestigationCase[];readonly findings_preserved:number;readonly rules_executed:readonly string[]}
export interface InvestigationReport{readonly run_id:string;readonly case_id:string;readonly kind:"executive"|"technical"|"analyst";readonly json:string;readonly html:string}

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const ITEM=/^(?:cluster-v1|case-v1)-[0-9a-f]{64}$/u;
const STATUSES=["suggested","open","investigating","remediating","verification_pending","resolved","accepted_risk","ignored"] as const;
const PRIORITIES=["immediate","high","normal","low","review"] as const;
const TARGET_TYPES=["repository","file","installed_application","web_url"] as const;
function object(value:unknown):Record<string,unknown>{if(value===null||typeof value!=="object"||Array.isArray(value))throw new Error("Backend response rejected");return value as Record<string,unknown>}
function exact(value:Record<string,unknown>,keys:readonly string[]){const a=Object.keys(value).sort(),b=[...keys].sort();if(a.length!==b.length||a.some((key,index)=>key!==b[index]))throw new Error("Backend response rejected")}
function text(value:unknown,max=512){if(typeof value!=="string"||value.length===0||value.length>max||/[\u0000-\u001f\u007f\u061c\u200e\u200f\u202a-\u202e\u2066-\u2069]/u.test(value))throw new Error("Backend response rejected");return value}
function jsonText(value:unknown,max:number){if(typeof value!=="string"||value.length<2||value.length>max||/[\u0000\u000b\u000c\u007f]/u.test(value))throw new Error("Backend response rejected");JSON.parse(value);return value}
function integer(value:unknown,max=100_000){if(!Number.isSafeInteger(value)||Number(value)<0||Number(value)>max)throw new Error("Backend response rejected");return Number(value)}
function texts(value:unknown,max=1000):readonly string[]{if(!Array.isArray(value)||value.length>max)return (()=>{throw new Error("Backend response rejected")})();return Object.freeze(value.map(item=>text(item,2048)))}
function id(value:unknown,pattern=ITEM){const result=text(value,128);if(!pattern.test(result))throw new Error("Backend response rejected");return result}
function parseTimeline(value:unknown):TimelineEvent{const v=object(value);exact(v,["sequence","timestamp","event_type","summary_safe","source"]);return Object.freeze({sequence:integer(v.sequence),timestamp:text(v.timestamp,40),event_type:text(v.event_type,80),summary_safe:text(v.summary_safe,512),source:text(v.source,80)})}
function parseTransition(value:unknown):CaseTransition{const v=object(value);exact(v,["from","to","timestamp","actor_source","reason_safe"]);if(!STATUSES.includes(v.from as CaseStatus)||!STATUSES.includes(v.to as CaseStatus))throw new Error("Backend response rejected");return Object.freeze({from:v.from as CaseStatus,to:v.to as CaseStatus,timestamp:text(v.timestamp,40),actor_source:text(v.actor_source,80),reason_safe:text(v.reason_safe,512)})}
export function parseCase(value:unknown):InvestigationCase{const v=object(value);exact(v,["case_id","title_safe","status","suggested","finding_ids","cluster_ids","entity_ids","evidence_ids","blast_radius","assessment","timeline","transitions"]);const b=object(v.blast_radius),a=object(v.assessment);exact(b,["observed_only","unique_affected_targets","unique_affected_components","unique_findings","unique_vulnerability_ids","target_types_affected"]);exact(a,["risk","confidence","coverage","priority","risk_reasons","confidence_reasons","coverage_reasons","priority_reasons"]);if(v.suggested!==true&&v.suggested!==false||b.observed_only!==true||!STATUSES.includes(v.status as CaseStatus)||!PRIORITIES.includes(a.priority as typeof PRIORITIES[number])||!Array.isArray(v.timeline)||v.timeline.length>2000||!Array.isArray(v.transitions)||v.transitions.length>2000)throw new Error("Backend response rejected");const targetTypes=texts(b.target_types_affected,16);if(targetTypes.some(value=>!TARGET_TYPES.includes(value as typeof TARGET_TYPES[number])))throw new Error("Backend response rejected");return Object.freeze({case_id:id(v.case_id),title_safe:text(v.title_safe,160),status:v.status as CaseStatus,suggested:v.suggested,finding_ids:texts(v.finding_ids),cluster_ids:texts(v.cluster_ids),entity_ids:texts(v.entity_ids),evidence_ids:texts(v.evidence_ids),blast_radius:Object.freeze({observed_only:true,unique_affected_targets:integer(b.unique_affected_targets),unique_affected_components:integer(b.unique_affected_components),unique_findings:integer(b.unique_findings),unique_vulnerability_ids:integer(b.unique_vulnerability_ids),target_types_affected:targetTypes}),assessment:Object.freeze({risk:integer(a.risk,100),confidence:integer(a.confidence,100),coverage:integer(a.coverage,100),priority:a.priority as string,risk_reasons:texts(a.risk_reasons,32),confidence_reasons:texts(a.confidence_reasons,32),coverage_reasons:texts(a.coverage_reasons,32),priority_reasons:texts(a.priority_reasons,32)}),timeline:Object.freeze(v.timeline.map(parseTimeline)),transitions:Object.freeze(v.transitions.map(parseTransition))})}
export function parseCluster(value:unknown):Cluster{const v=object(value);exact(v,["cluster_id","cluster_type","member_findings","member_entities","supporting_edges","target_count","evidence_count","first_seen","last_seen","explanation_safe"]);return Object.freeze({cluster_id:id(v.cluster_id),cluster_type:text(v.cluster_type,64),member_findings:texts(v.member_findings),member_entities:texts(v.member_entities),supporting_edges:texts(v.supporting_edges),target_count:integer(v.target_count),evidence_count:integer(v.evidence_count),first_seen:text(v.first_seen,40),last_seen:text(v.last_seen,40),explanation_safe:text(v.explanation_safe,1024)})}
function parseSummary(value:unknown):CorrelationSummary{const v=object(value);exact(v,["run_id","state","limit_reached","replay_match","nodes","relationships","clusters","cases"]);if(!["complete","partial_correlation","cancelled"].includes(String(v.state))||typeof v.limit_reached!=="boolean"||typeof v.replay_match!=="boolean"||(v.state==="complete"&&(!v.replay_match||v.limit_reached))||(v.state==="partial_correlation"&&!v.limit_reached)||(v.state==="cancelled"&&v.limit_reached))throw new Error("Backend response rejected");return Object.freeze({run_id:id(v.run_id,UUID),state:v.state as CorrelationRunState,limit_reached:v.limit_reached,replay_match:v.replay_match,nodes:integer(v.nodes),relationships:integer(v.relationships),clusters:integer(v.clusters),cases:integer(v.cases)})}
function parsePage<T>(value:unknown,parser:(item:unknown)=>T):readonly T[]{const v=object(value);exact(v,["items","offset","limit"]);if(!Array.isArray(v.items)||v.items.length>100||integer(v.offset,10000)!==0||integer(v.limit,100)!==100)throw new Error("Backend response rejected");return Object.freeze(v.items.map(parser))}
function parseGraph(value:unknown):InvestigationGraph{
  const v=object(value);
  exact(v,["schema","state","limit_reached","nodes","edges","clusters","suggested_cases","findings_preserved","rules_executed"]);
  if(v.schema!=="LEVEL5_INVESTIGATION_V1"||v.state!=="complete"||v.limit_reached!==false||!Array.isArray(v.nodes)||v.nodes.length>10000||!Array.isArray(v.edges)||v.edges.length>20000||!Array.isArray(v.clusters)||v.clusters.length>1000||!Array.isArray(v.suggested_cases)||v.suggested_cases.length>1000)throw new Error("Backend response rejected");
  const edges=v.edges.map(item=>{
    const e=object(item);
    exact(e,["edge_id","relationship","from_entity","to_entity","rule_id","rule_version","finding_ids","evidence_ids","source_scans","created_by","confidence","reasoning_safe","schema_version"]);
    return Object.freeze({edge_id:text(e.edge_id,128),relationship:text(e.relationship,80),from_entity:text(e.from_entity,128),to_entity:text(e.to_entity,128),rule_id:text(e.rule_id,128),rule_version:integer(e.rule_version,100),finding_ids:texts(e.finding_ids,1000),evidence_ids:texts(e.evidence_ids,32),source_scans:texts(e.source_scans,32),created_by:text(e.created_by,80),confidence:integer(e.confidence,100),reasoning_safe:text(e.reasoning_safe,2048),schema_version:integer(e.schema_version,100)});
  });
  const nodes=v.nodes.map(item=>{
    const n=object(item),identity=object(n.identity);
    exact(n,["entity_id","schema","kind","identity","label_safe"]);
    exact(identity,["kind","canonical_value"]);
    return Object.freeze({entity_id:text(n.entity_id,128),schema:text(n.schema,80),kind:text(n.kind,64),identity:Object.freeze({kind:text(identity.kind,64),canonical_value:text(identity.canonical_value,2048)}),label_safe:text(n.label_safe,160)});
  });
  return Object.freeze({schema:"LEVEL5_INVESTIGATION_V1",state:"complete",limit_reached:false,nodes:Object.freeze(nodes),edges:Object.freeze(edges),clusters:Object.freeze(v.clusters.map(parseCluster)),suggested_cases:Object.freeze(v.suggested_cases.map(parseCase)),findings_preserved:integer(v.findings_preserved),rules_executed:texts(v.rules_executed,32)});
}
export { parseGraph };
async function call<T>(command:string,args:Record<string,unknown>,parser:(value:unknown)=>T):Promise<T>{return parser(await invoke(command,args))}
const page=(runId:string)=>({request:{run_id:id(runId,UUID),offset:0,limit:100}});
const item=(runId:string,itemId:string)=>({request:{run_id:id(runId,UUID),item_id:id(itemId)}});
export const level5Api=Object.freeze({
  run:()=>call("run_level5_correlation",{},parseSummary),
  cancel:()=>call("cancel_level5_correlation",{},value=>{if(typeof value!=="boolean")throw new Error("Backend response rejected");return value}),
  clusters:(runId:string)=>call("list_investigation_clusters",page(runId),value=>parsePage(value,parseCluster)),
  cases:(runId:string)=>call("list_investigation_cases",page(runId),value=>parsePage(value,parseCase)),
  graph:(runId:string)=>call("get_investigation_graph",{request:{run_id:id(runId,UUID)}},parseGraph),
  createCase:(runId:string,clusterId:string)=>call("create_investigation_case",item(runId,clusterId),parseCase),
  transition:(runId:string,caseId:string,status:CaseStatus)=>call("update_investigation_case",{request:{run_id:id(runId,UUID),case_id:id(caseId),status,reason_safe:"Explicit analyst lifecycle action"}},parseCase),
  report:(runId:string,caseId:string,kind:InvestigationReport["kind"])=>call("generate_investigation_report",{request:{run_id:id(runId,UUID),case_id:id(caseId),kind}},value=>{const v=object(value);exact(v,["run_id","case_id","kind","json","html"]);if(v.kind!==kind)throw new Error("Backend response rejected");const json=jsonText(v.json,8*1024*1024),html=text(v.html,8*1024*1024);return Object.freeze({run_id:id(v.run_id,UUID),case_id:id(v.case_id),kind,json,html})}),
});
